create database customer_data;
use customer_data;

select * from mytable limit 10;

#Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as pd
from mytable
group by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from mytable);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
AVG(purchase_amount)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
count(customer_id),
avg(purchase_amount),
sum(purchase_amount) 
from mytable
group by subscription_status;

-- Q6 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q7. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;
